services:
  cache:
    image: redis:8
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      cache:
        condition: service_healthy
    environment:
      CACHE_ADDR: cache:6379
      LOG_LEVEL: DEBUG
      OPENAI_API_KEY: ${OPENAI_API_KEY}
